### ISSUE TITLE
PSR-15 compatibility for zend-expressive

### ISSUE THREAD

**Issue by spotman** [php-middleware/request-id#12]
Hi there!

I'm trying to use your library in `zend-expressive` v3.2 but it gives me an error:

`Service "PhpMiddleware\RequestId\RequestIdMiddleware" did not to resolve to a Psr\Http\Server\MiddlewareInterface instance; resolved to "PhpMiddleware\RequestId\RequestIdMiddleware"`

Is it possible to use your library in a PSR-15 context with `\Psr\Server\Http\MiddlewareInterface` support?

**Comment by snapshotpl** [comment]
@spotman done :)
