### ISSUE TITLE
Add an open-source license, please?

### ISSUE THREAD

**Issue by skyzyx** [php-middleware/request-id#9]
(Cross posted to https://github.com/php-middleware/log-http-messages/issues/5)

I'm doing a review of the software licenses in my package dependencies, and realized that this package does not have a license listed by `composer licenses`. Here's a quick run-down of the bigger software license groups — just in case you're not aware.

"No license" means that nobody is allowed to use your code, legally. As the author and copyright owner, this means that nobody else can — legally — use this software except for you.

GPL (or anything from the FSF) are _free-software_ licenses. They are viral by design, which means that they generally include clauses about patent rights, (forced) redistribution, and/or forcing integrators to re-license their code to match your license. (I, and many others, would have to stop using this package to protect ourselves, legally.)

BSD 3-clause, BSD 2-clause, MIT, PHP, and Apache 2.0 are all _open-source_ licenses. They generally allow free use — by anyone, for any purpose — as long as you don't violate their trademarks or make it sound like they endorse your project. Both BSD flavors and the MIT license are short and sweet, but ambiguous. PHP is pretty much for the PHP team, but many people use it anyways for their PHP-based projects. Apache 2.0 is published by the Apache Foundation and is generally unambiguous, legally. Corporate lawyers tend to prefer it for this reason.

My request is that you license this code using an _open-source_ license.

**Comment by snapshotpl** [comment]
@skyzyx https://github.com/php-middleware/request-id/releases/tag/3.1.1 :)
